version: '3'
services:
  backend:
    build: ./contact-manager-backend
    ports:
      - '4000:4000'
    environment:
      DATABASE_URL: postgresql://postgres:123@db:5432/postgres
    depends_on:
      db:
        condition: service_healthy
    networks:
      - contacts-network
      
  frontend:
    build: ./contact-manager-frontend
    ports:
      - '3000:3000'

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - contacts-network
    volumes:
      - db_data:/var/lib/postgresql/data
    

volumes:
  db_data:

networks:
  contacts-network: 
    driver: "bridge"