version: '3'
services:
  backend:
    build: ./contact-manager-backend
    ports:
      - '4000:4000'
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./contact-manager-frontend
    ports:
      - '3000:3000'

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: contacts
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
